apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: front-end
  namespace: sock-shop
spec:
  gateways:
    - sock-shop-gateway
  hosts:
    - "*"
  http:
    - route:
        - destination:
            host: front-end
          weight: 100
      match:
        - uri:
            prefix: "/"
