apiVersion: flagger.app/v1beta1
kind: MetricTemplate
metadata:
  name: request-success-rate-custome
  namespace: istio-system
spec:
  provider:
    type: prometheus
    address: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
  query: |
    sum(
      rate(
          istio_requests_total{
            reporter="destination",
            destination_workload_namespace=~"{{ namespace }}",
            destination_workload=~"{{ target }}",
            response_code!~"5.*"
          }[{{ interval }}]
      )
    ) 
    / 
    sum(
        rate(
            istio_requests_total{
              reporter="destination",
              destination_workload_namespace=~"{{ namespace }}",
              destination_workload=~"{{ target }}"
            }[{{ interval }}]
        )
    )

---
apiVersion: flagger.app/v1beta1
kind: MetricTemplate
metadata:
  name: request-duration-custome
  namespace: istio-system
spec:
  provider:
    type: prometheus
    address: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
  query: |
    histogram_quantile(0.95, 
      sum(
        irate(
          istio_request_duration_milliseconds_bucket{
            reporter="destination",
            destination_workload=~"front-end",
            destination_workload_namespace=~"sock-shop"
          }[2m]
        )
      ) by (le)
    )
