apiVersion: loadtest.jmeter.com/v1alpha1
kind: Jmeter
metadata:
  name: jmeter-loadtest
  namespace: jmeter
spec:
  # Add fields here
  slave_size: 0
  jmeter_master_image: kubernautslabs/jmeter_master:latest
  jmeter_slave_image: kubernautslabs/jmeter_slave:latest
  # grafana_server_root: /
  # grafana_service_type: LoadBalancer
  # grafana_image: grafana/grafana:5.2.0
  influxdb_image: influxdb
  grafana_install: "false"
  grafana_reporter_install: "true"
  grafana_reporter_image: kubernautslabs/jmeter-reporter:latest
  influxdb_install: "true"
