apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    jmeter_mode: jmeter-loadtest-jmeter-master
  name: jmeter-loadtest-jmeter-master
  namespace: jmeter
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      jmeter_mode: jmeter-loadtest-jmeter-master
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        jmeter_mode: jmeter-loadtest-jmeter-master
    spec:
      containers:
      - args:
        - while true; do sleep 30; done;
        command:
        - /bin/bash
        - -c
        - --
        image: kubernautslabs/jmeter_master:latest
        imagePullPolicy: IfNotPresent
        name: jmetermaster
        ports:
        - containerPort: 60000
          protocol: TCP
        resources: 
          requests: 
            memory: 2000Mi
          limits:
            memory: 2000Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /load_test
          name: loadtest
          subPath: load_test
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: jmeter-loadtest-jmeter-master-config
        name: loadtest
