apiVersion: v1
data:
  influxdb.conf: |
    reporting-disabled = true
    [meta]
      dir = "/var/lib/influxdb/meta"
    [data]
      dir = "/var/lib/influxdb/data"
      engine = "tsm1"
      wal-dir = "/var/lib/influxdb/wal"
    # Configure the graphite api
    [[graphite]]
    enabled = true
    bind-address = ":2003" # If not set, is actually set to bind-address.
    database = "jmeter"  # store graphite data in this database
kind: ConfigMap
metadata:
  labels:
    jmeter_mode: jmeter-loadtest-influxdb
  name: jmeter-loadtest-influxdb-config
  namespace: jmeter
