apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - jmeter-loadtest-influxdb-dep.yaml
  - jmeter-loadtest-influxdb-svc.yaml
  - jmeter-loadtest-influxdb-cm.yaml
  - jmeter-loadtest-jmeter-master-dep.yaml
  - jmeter-loadtest-jmeter-master-cm.yaml
  - jmeter-flagger-dep.yaml
  - jmeter-flagger-svc.yaml

configMapGenerator:
  - name: jmeter-scenario-load-test
    files:
      - scenario.jmx
  - name: jmeter-scenario-user-preparation
    files:
      - preparation.jmx
