{
 "title": "JMeter Metric",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "app",
    "query": "SHOW TAG VALUES FROM \"process\" WITH KEY = \"application\""
   },
   { "name": "granularity", "query": "1m,5m,1h,5s,15s,30s" },
   {
    "name": "retention",
    "query": "SHOW RETENTION POLICIES ON \"jmeter\""
   },
   {
    "name": "transaction",
    "query": "SHOW TAG VALUES FROM \"jmeter\" WITH KEY IN (\"transaction\",\"application\") where application =~ /$app/ and transaction  !~ /all/"
   },
   { "name": "transaction_prefix", "label": "TransactionPrefix", "query": "TRN" }
  ]
 },
 "panels": [
  {
   "title": "Flagger log",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{app_kubernetes_io_name=\"flagger\"}"
    }
   ]
  },
  {
   "title": "Jmeter log",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "{app=\"loadtester\"}"
    }
   ]
  },
  { "title": "Jmeter Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Total Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "TPS",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT last(\"hit\")  / 5 FROM \"jmeter\" WHERE \"application\" =~ /$app$/ AND $timeFilter GROUP BY time($granularity) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 30" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/$app$/" },
      { "condition": "AND", "key": "statut", "operator": "<>", "value": "ok" },
      { "condition": "AND", "key": "responseCode", "operator": "<>", "value": "0" },
      { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/URL/" }
     ]
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$granularity" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT last(\"startedT\") FROM \"jmeter\" WHERE \"application\" =~ /$app$/ AND $timeFilter GROUP BY time($granularity) fill(null)",
     "select": [
      [
       { "params": [ "meanAT" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/$app$/" }
     ]
    }
   ]
  },
  {
   "title": "Errors per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Errors",
     "groupBy": [
      { "params": [ "$granularity" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT mean(\"countError\")  / 5 FROM \"jmeter\" WHERE \"application\" =~ /$app$/ AND $timeFilter GROUP BY time($granularity) fill(0)",
     "select": [
      [
       { "params": [ "countError" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 5" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/$app$/" }
     ]
    }
   ]
  },
  { "title": "Application Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 }, "repeat": "app" },
  {
   "title": "Transaction Per Second",
   "type": "graph",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$tag_transaction",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "measurement": "jmeter",
     "query": "SELECT mean(\"count\")  / 5 FROM \"jmeter\" WHERE \"application\" =~ /$app$/ AND \"transaction\" <> 'all' AND $timeFilter GROUP BY time($granularity), \"transaction\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 30" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/$app$/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "transaction", "operator": "<>", "value": "all" },
      { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/URL/" }
     ]
    }
   ]
  },
  {
   "title": "90%ile Response Time - PV",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_transaction",
     "groupBy": [
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "measurement": "jmeter",
     "query": "SELECT mean(\"avg\") FROM \"jmeter\" WHERE \"application\" =~ /$app$/ AND $timeFilter GROUP BY time($granularity), \"transaction\"",
     "select": [
      [
       { "params": [ "pct90.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/$app$/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "transaction", "operator": "!~", "value": "/URL/" }
     ]
    }
   ]
  },
  {
   "title": "90%ile Response Time - URL detail",
   "type": "graph",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_transaction",
     "groupBy": [
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "measurement": "jmeter",
     "query": "SELECT mean(\"avg\") FROM \"jmeter\" WHERE \"application\" =~ /$app$/ AND $timeFilter GROUP BY time($granularity), \"transaction\"",
     "select": [
      [
       { "params": [ "pct90.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/$app$/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/URL/" }
     ]
    }
   ]
  },
  {
   "title": "Percentile Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$granularity" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT mean(\"pct90.0\") as \"90percentile\", mean(\"pct95.0\") as \"95percentile\" FROM \"$retention\".\"jmeter\" WHERE $timeFilter GROUP BY time($granularity)",
     "select": [
      [
       { "params": [ "pct90.0" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "90 percentile" ], "type": "alias" }
      ],
      [
       { "params": [ "pct95.0" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "95 percentile" ], "type": "alias" }
      ],
      [
       { "params": [ "pct99.0" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "99 percentile" ], "type": "alias" }
      ],
      [
       { "params": [ "min" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Min" ], "type": "alias" }
      ],
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Max" ], "type": "alias" }
      ],
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Avg" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/$app$/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "Throughput Vs Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$granularity" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT mean(\"pct90.0\") as \"90percentile\", mean(\"pct95.0\") as \"95percentile\" FROM \"$retention\".\"jmeter\" WHERE $timeFilter GROUP BY time($granularity)",
     "select": [
      [
       { "params": [ "pct90.0" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "ResponseTime" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/$app$/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "all" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"count\")  / 30  as TPS FROM \"$retention\".\"jmeter\" WHERE (\"application\" =~ /$app$/ AND \"transaction\" <> 'all' AND \"statut\" = 'all') AND $timeFilter GROUP BY time(30s) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Success/Error Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "ErrorTPS",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" }
     ],
     "measurement": "jmeter",
     "query": "SELECT mean(\"count\")  / 5 FROM \"jmeter\" WHERE \"application\" =~ /$app$/ AND \"transaction\" <> 'all' AND $timeFilter GROUP BY time($granularity), \"transaction\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 30" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/$app$/" },
      { "condition": "AND", "key": "transaction", "operator": "<>", "value": "all" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    },
    {
     "alias": "SuccessTPS",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" }
     ],
     "measurement": "jmeter",
     "query": "SELECT mean(\"count\")  / 5 FROM \"jmeter\" WHERE \"application\" =~ /$app$/ AND \"transaction\" <> 'all' AND $timeFilter GROUP BY time($granularity), \"transaction\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 30" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/$app$/" },
      { "condition": "AND", "key": "transaction", "operator": "<>", "value": "all" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    }
   ]
  },
  {
   "title": "Error Per Second",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$tag_transaction",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "transaction" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT last(\"count\")  / 30 FROM \"$retention\".\"jmeter\" WHERE \"application\" =~ /$app$/ AND \"statut\" = 'ko' AND $timeFilter GROUP BY time(30s), \"transaction\" fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 30" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/$app$/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    }
   ]
  },
  {
   "title": "Error detail",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_transaction - $tag_responseCode : $tag_responseMessage",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "responseMessage" ], "type": "tag" },
      { "params": [ "responseCode" ], "type": "tag" },
      { "params": [ "transaction" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT last(\"count\")  / 30 FROM \"$retention\".\"jmeter\" WHERE \"application\" =~ /$app$/ AND \"statut\" = 'ko' AND $timeFilter GROUP BY time(30s), \"transaction\" fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 30" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/$app$/" },
      { "condition": "AND", "key": "responseCode", "operator": "!~", "value": "/^0$|^$/" }
     ]
    }
   ]
  }
 ]
}