{
 "title": "Pod All Dashborad",
 "description": "A dashboard to view pod metrics by namespace and pod names.\r\n\r\nUse this Helm chart to launch Grafana into a Kubernetes cluster. It will include this dashboard and many more dashboards to give you visibility into the Kubernetes Cluster. (https://github.com/sekka1/cloud-public/tree/master/kubernetes/pods/grafana-helm)",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_namespace_labels, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_container_info{namespace=\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(container_cpu_usage_seconds_total{pod!=\"\", pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\"}[5m]) * 100) by (pod)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod!=\"\", pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Nginx Upstream Response time (msec)",
   "type": "graph",
   "description": "nginx_upstream_response_msecs_avg",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nginx_upstream_response_msecs_avg{upstream=~\"[[namespace]].*\"}"
    }
   ]
  },
  {
   "title": "nginx_connections_total - 1m",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (type) (irate(nginx_connections_total[1m]) )",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Network RX",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(container_network_receive_bytes_total{pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\"}[5m])) by (pod)"
    }
   ]
  },
  {
   "title": "Network TX",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(container_network_transmit_bytes_total{pod=~\"[[pod]].*\", namespace=~\"[[namespace]].*\"}[5m])) by (pod)"
    }
   ]
  }
 ]
}